[package]
name = "arche"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.3"
chrono = "0.4.41"
chrono-tz = "0.10.3"
dotenvy = "0.15.7"
rand = "0.9.1"
serenity = "0.12.4"
tokio = { version = "1.44.2", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
